# Generated by Django 5.0.1 on 2024-01-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0003_approval_delete_approvals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='applicantincome',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='approval',
            name='area',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Semiurban', 'Semiurban'), ('Rural', 'Rural')], max_length=15),
        ),
        migrations.AlterField(
            model_name='approval',
            name='coapplicantincome',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='approval',
            name='credithistory',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='approval',
            name='dependants',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='approval',
            name='graduatededucation',
            field=models.CharField(choices=[('Not_Graduate', 'Not_Graduate'), ('Graduate', 'Graduate')], max_length=15),
        ),
        migrations.AlterField(
            model_name='approval',
            name='loanamt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='approval',
            name='loanterm',
            field=models.IntegerField(),
        ),
    ]
