# Generated by Django 5.0.1 on 2024-01-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0004_alter_approval_applicantincome_alter_approval_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='area',
            field=models.CharField(choices=[('Semiurban', 'Semiurban'), ('Urban', 'Urban'), ('Rural', 'Rural')], max_length=15),
        ),
        migrations.AlterField(
            model_name='approval',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=15),
        ),
        migrations.AlterField(
            model_name='approval',
            name='graduatededucation',
            field=models.CharField(choices=[('Graduate', 'Graduate'), ('Not_Graduate', 'Not_Graduate')], max_length=15),
        ),
    ]
