# Generated by Django 5.0.1 on 2024-01-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0005_alter_approval_area_alter_approval_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15),
        ),
        migrations.AlterField(
            model_name='approval',
            name='graduatededucation',
            field=models.CharField(choices=[('Not_Graduate', 'Not_Graduate'), ('Graduate', 'Graduate')], max_length=15),
        ),
        migrations.AlterField(
            model_name='approval',
            name='married',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=15),
        ),
        migrations.AlterField(
            model_name='approval',
            name='selfemployed',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=15),
        ),
    ]
